- name: Determine if node is part of a cluster
  shell: grep -q "$(hostname)" "/mnt/state/var/lib/rabbitmq/mnesia/rabbit@$(hostname)/cluster_nodes.config"
  ignore_errors: yes
  register: rabbit_cluster_test
- name: If node rabbitmq cluster config was present, prevent os-refresh-config post-configure.d job from executing.
  file: mode=0644 path=/opt/stack/os-config-refresh/post-configure.d/40-rabbitmq
  when: rabbit_cluster_test.rc == 0
