# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Call nova_rebuild if instance needs to be updated"
  nova_rebuild:
    instance_id: "{{ instance_id }}"
    image_id: "{{ rebuild_image_id }}"
    preserve_ephemeral: true
    wait: "yes"
    wait_for: 900
  delegate_to: localhost
  when: instance_image_id != rebuild_image_id and force_rebuild is not defined
- name: "Call nova_rebuild if rebuild is mandated"
  nova_rebuild:
    instance_id: "{{ instance_id }}"
    image_id: "{{ rebuild_image_id }}"
    preserve_ephemeral: true
    wait: "yes"
    wait_for: 900
  delegate_to: localhost
  when: force_rebuild is defined
