# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# This is primarilly due to the fact that we can possibly interrupt existing
# start-up sequences before this is done depending on system performance, and
# as a result be unable later on to start services such as rabbitmq-server.
#
# This at some point should be replaced with comperable code in Ansible
# to have the same end effect.
- name: Trigger hosts file generation
  sudo: yes
  command: /opt/stack/os-config-refresh/configure.d/51-hosts
